apiVersion: apps/v1
kind: Deployment
metadata:
  name: classification-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classification-backend
  template:
    metadata:
      labels:
        app: classification-backend
    spec:
      containers:
        - name: backend
          image: chaymae01/classification-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          
  
---
apiVersion: v1
kind: Service
metadata:
  name: classification-backend-service
spec:
  selector:
    app: classification-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
